title: Patriklauzirika's Portfolio
description: Welcome to my GitHub Pages site
theme: jekyll-theme-minimal

# Site settings
url: "https://patriklauzirika.github.io"
baseurl: ""

# Author info
author: Patriklauzirika
email: your-email@example.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
